server {
    listen 80;
    server_name localhost;
    # Tự động chuyển hướng từ HTTP sang HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/ssl/localhost.crt;
    ssl_certificate_key /etc/nginx/ssl/localhost.key;

    root /usr/share/nginx/html;
    index index.html;

    # Thêm dòng này để cho phép Stripe chạy ổn định
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' https://js.stripe.com https://m.stripe.network 'unsafe-inline'; worker-src 'self' blob:; connect-src 'self' https://api.stripe.com; frame-src https://js.stripe.com https://hooks.stripe.com; img-src 'self' data: https://*.stripe.com;";

    location / {
        # Quan trọng cho Angular Routing: Nếu không tìm thấy file, trả về index.html
        try_files $uri $uri/ /index.html;
    }
}